[2017-01-11 10:43:57] mautic.WARNING: IP LOOKUP: The file "/opt/bitnami/apps/mautic/htdocs/app/cache/prod/../ip_data/GeoLite2-City.mmdb" does not exist or is not readable. [] []
[2017-01-11 13:39:03] mautic.WARNING: IP LOOKUP: The file "/opt/bitnami/apps/mautic/htdocs/app/cache/prod/../ip_data/GeoLite2-City.mmdb" does not exist or is not readable. [] []
[2017-01-11 13:39:05] mautic.WARNING: IP LOOKUP: The file "/opt/bitnami/apps/mautic/htdocs/app/cache/prod/../ip_data/GeoLite2-City.mmdb" does not exist or is not readable. [] []
[2017-01-11 13:39:07] mautic.WARNING: IP LOOKUP: The file "/opt/bitnami/apps/mautic/htdocs/app/cache/prod/../ip_data/GeoLite2-City.mmdb" does not exist or is not readable. [] []
[2017-01-11 15:08:32] mautic.ERROR: Error: Call to a member function getId() on null - in file /opt/bitnami/apps/mautic/htdocs/plugins/MauticContactEventBundle/Controller/ContactApiController.php - at line 169 [] []
[2017-01-11 10:11:20] mautic.ERROR: Error: Call to a member function getId() on null - in file /opt/bitnami/apps/mautic/htdocs/plugins/MauticContactEventBundle/Controller/ContactApiController.php - at line 169 [] []
